### ISSUE TITLE
Create a requirements.txt for Python dependencies

### ISSUE THREAD

**Issue by Jolg42** [malteserteresa/stop-it#10]
I'm not a pythonista but I'm used to find a `requirements.txt` to get a perfect replica of the installed dependencies.

Could you run `conda list -e > requirements.txt`?
After that I don't know how it works but there is probably a command to tell conda to install the dependencies from the .txt file? 

Also do you know how to install `conda` easily on macOS?

**Comment by MikeJohnPage** [comment]
@Jolg42 please see the updated 'Installation Instructions' in the [README](https://github.com/malteserteresa/stop-it/blob/master/README.md). There is now a link to macOS specific [installation instructions](https://docs.conda.io/projects/conda/en/latest/user-guide/install/macos.html). There is also updated instructions on how to install the dependencies. You just need to run the following command from the terminal after conda has been installed:
```
conda create --name stop-it tensorflow keras numpy pandas flask matplotlib scikit-learn pytest
```
If you have any problems let us know.
