### ISSUE TITLE
Adding Code of Conduct in repository

### ISSUE THREAD

**Issue by Jolg42** [malteserteresa/stop-it#12]
Right now there is a link to https://www.contributor-covenant.org/ in the contributing.md file but it would be better to have in the repo with an email to contact.

To add it it looks like we need to do:
```
npm install -g covgen
covgen <your_email_address>
```

Not sure about which email address to put though :)

**Comment by MikeJohnPage** [comment]
Thanks for the info. The repo has now been updated to reflect these changes.
