### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by MikeJohnPage** [malteserteresa/stop-it#5]
When using conda, `tensorflow 1.12.2` [isn't available](https://anaconda.org/conda-forge/tensorflow/files). More recent versions are. Additionally, matplotlib needs to be listed in the requirements. Perhaps the following code should be included in the README.md file:

`conda create --name stop-it tensorflow keras numpy pandas flask matplotlib`

**Comment by malteserteresa** [comment]
great idea

**Comment by MikeJohnPage** [comment]
more issue requirements inc. scikit-learn etc. I will update the README.md shortly
